"""Bulk-versus-boundary SHAP attribution table."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import polars as pl

BULK_SHARE_FLOOR = 0.005
RISE_THRESHOLD = 1.10
TOP_N = 14
N_RISERS = 3

BOUNDARY_MAX_U_S = 1800.0
BULK_MIN_U_S = 7200.0

SHAP_PREFIX = "shap__"


def _window_shares(df: pl.DataFrame, features: list[str]) -> tuple[dict[str, float], dict[str, float], int, float]:
    """HT-weighted mean |SHAP| and attribution share for one window."""
    w = df["weight"].to_numpy()
    w_sum = float(w.sum())
    means = {
        f: float((df[SHAP_PREFIX + f].abs().to_numpy() * w).sum() / w_sum)
        for f in features
    }
    total = sum(means.values())
    shares = {f: m / total for f, m in means.items()}
    return means, shares, df.height, w_sum


def _fmt_pct(x: float) -> str:
    return f"{100.0 * x:.1f}\\%"


def _esc(name: str) -> str:
    return name.replace("_", r"\_")


def build_table(bulk: dict[str, float], bnd: dict[str, float],
                n_bnd: int, n_bulk: int) -> str:
    ratio = {f: bnd[f] / bulk[f] for f in bulk}
    top = sorted(bulk, key=lambda f: -bulk[f])[:TOP_N]
    risers = [
        f for f in bulk
        if f not in top and bulk[f] >= BULK_SHARE_FLOOR and ratio[f] >= RISE_THRESHOLD
    ]
    risers.sort(key=lambda f: -ratio[f])
    risers = risers[:N_RISERS]

    def row(f: str) -> str:
        mark = r"$^{\uparrow}$" if ratio[f] >= RISE_THRESHOLD else ""
        return (f"{_esc(f)}{mark} & {_fmt_pct(bulk[f])} & {_fmt_pct(bnd[f])} "
                f"& {ratio[f]:.2f} \\\\")

    lines = [
        "% Generated by analysis_shap_boundary.py. Attribution share =",
        "% feature mean |SHAP| / sum over features, per u window,",
        "% Horvitz-Thompson weighted over the 64-fold OOS sample.",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"feature & bulk share & boundary share & ratio \\",
        r"\midrule",
        *[row(f) for f in top],
        r"\midrule",
        *[row(f) for f in risers],
        r"\midrule",
        (r"\multicolumn{4}{l}{boundary = $u \le 30$ min (" f"{n_bnd:,}"
         r" rows), bulk = $u > 2$ h (" f"{n_bulk:,}" r" rows).} \\"),
        (r"\multicolumn{4}{l}{Above the rule: largest features by bulk share. "
         r"Below it: the smaller features whose} \\"),
        (r"\multicolumn{4}{l}{share rises most toward the settlement; "
         r"$^{\uparrow}$ = boundary share $\ge 1.1\times$ bulk share.} \\"),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--shap-values", type=Path, required=True)
    ap.add_argument("--report-dir", type=Path, default=Path("reports"))
    args = ap.parse_args()

    df = pl.read_parquet(args.shap_values)
    features = [c[len(SHAP_PREFIX):] for c in df.columns if c.startswith(SHAP_PREFIX)]

    bnd_df = df.filter(pl.col("u_s") <= BOUNDARY_MAX_U_S)
    bulk_df = df.filter(pl.col("u_s") > BULK_MIN_U_S)

    bnd_mean, bnd_share, bnd_n, bnd_w = _window_shares(bnd_df, features)
    bulk_mean, bulk_share, bulk_n, bulk_w = _window_shares(bulk_df, features)

    args.report_dir.mkdir(parents=True, exist_ok=True)
    tex = build_table(bulk_share, bnd_share, round(bnd_w), round(bulk_w))
    (args.report_dir / "tab_shap_boundary.tex").write_text(tex)

    payload = {
        "source": str(args.shap_values),
        "n_folds": int(df["fold"].n_unique()),
        "buckets": {
            "boundary": {"n_rows_sampled": bnd_n, "n_rows_weighted": bnd_w,
                         "mean_abs_shap": bnd_mean, "share": bnd_share},
            "bulk": {"n_rows_sampled": bulk_n, "n_rows_weighted": bulk_w,
                     "mean_abs_shap": bulk_mean, "share": bulk_share},
        },
    }
    (args.report_dir / "shap_boundary.json").write_text(json.dumps(payload, indent=1))

    print(f"{args.report_dir/'tab_shap_boundary.tex'}")
    print(f"   folds={payload['n_folds']}  boundary={bnd_n} sampled / "
          f"{bnd_w:,.0f} weighted   bulk={bulk_n} / {bulk_w:,.0f}")
    for f in sorted(bulk_share, key=lambda x: -bulk_share[x])[:6]:
        print(f"   {f:22s} bulk {100*bulk_share[f]:5.2f}%  bnd {100*bnd_share[f]:5.2f}%"
              f"  ratio {bnd_share[f]/bulk_share[f]:.2f}")


if __name__ == "__main__":
    main()
