"""Per-strategy P&L analysis for the six-strategy ablation."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from statistical_tests import (
    benjamini_hochberg,
    block_bootstrap_ci,
    block_bootstrap_diff_ci,
    block_bootstrap_interaction_ci,
    sharpe_ratio,
    sharpe_ratio_test,
)

STRATEGY_LABELS = {
    1: "1 Naive",
    2: "2 GLT",
    3: "3 GLT+AR",
    4: "4 GLT+ML",
    5: "5 GLT+Fund",
    6: "6 Full hybrid",
}
KEY_PAIRS = [(2, 6), (4, 6), (5, 6), (3, 4), (2, 4), (2, 5)]
INTERACTION_SPEC = (6, 5, 4, 2)
ANN = math.sqrt(365.0)


def discover_strategies(run_dir: Path) -> list[int]:
    return sorted(int(p.name[1:]) for p in run_dir.glob("s[0-9]") if p.is_dir())


def load_daily_panel(run_dir: Path) -> pl.DataFrame:
    """Tidy panel: one row per (funding_day, strategy) from the summary JSONs."""
    rows = []
    for sid in discover_strategies(run_dir):
        for p in sorted((run_dir / f"s{sid}").glob("summary_*.json")):
            d = json.loads(p.read_text())
            rows.append({
                "funding_day": d["funding_day"],
                "strategy": sid,
                "pnl": d["terminal_pnl"],
                "fees": d["fees"],
                "funding": d["funding"],
                "n_fills": d["n_fills"],
                "mean_abs_inv": d["mean_abs_inv"],
                "frac_time_at_cap": d["frac_time_at_cap"],
                "downtime_s": d["downtime_s"],
            })
    if not rows:
        raise FileNotFoundError(f"no summary_*.json under {run_dir}/s*/")
    return pl.DataFrame(rows).sort(["strategy", "funding_day"])


def daily_pnl_matrix(panel: pl.DataFrame) -> tuple[list[str], dict[int, np.ndarray]]:
    """Common-day daily P&L vectors per strategy (paired across strategies)."""
    sids = sorted(panel["strategy"].unique().to_list())
    daysets = [set(panel.filter(pl.col("strategy") == s)["funding_day"])
               for s in sids]
    days = sorted(set.intersection(*daysets))
    out = {}
    for s in sids:
        sub = (panel.filter(pl.col("strategy") == s)
               .filter(pl.col("funding_day").is_in(days))
               .sort("funding_day"))
        out[s] = sub["pnl"].to_numpy().astype(float)
    return days, out


def max_drawdown(daily: np.ndarray) -> float:
    cum = np.cumsum(daily)
    peak = np.maximum.accumulate(cum)
    return float(np.max(peak - cum))


def attribution_for_day(fills: pl.DataFrame, summary: dict) -> dict:
    """The five-component P&L decomposition."""
    mk = (fills.filter(~pl.col("is_liquidation"))
          if fills.height else fills)
    if mk.height:
        side = mk["side"].to_numpy().astype(float)
        qty = mk["qty"].to_numpy().astype(float)
        px = mk["price"].to_numpy().astype(float)
        m0 = mk["mid_0s"].to_numpy().astype(float)
        m5 = mk["mid_5s"].to_numpy().astype(float)
        ok0 = np.isfinite(m0)
        spread = float(np.sum(np.where(ok0, side * (m0 - px) * qty, 0.0)))
        ok5 = ok0 & np.isfinite(m5)
        advsel = float(np.sum(np.where(ok5, side * (m5 - m0) * qty, 0.0)))
    else:
        spread = advsel = 0.0
    funding = float(summary["funding"])
    fees = float(summary["fees"])
    terminal = float(summary["terminal_pnl"])
    residual = terminal - (spread + advsel + funding - fees)
    return {"spread_capture": spread, "adverse_selection_5s": advsel,
            "funding": funding, "fees": -fees,
            "inventory_residual": residual, "terminal": terminal}


def load_attribution(run_dir: Path, sid: int) -> pl.DataFrame:
    rows = []
    sdir = run_dir / f"s{sid}"
    for sp in sorted(sdir.glob("summary_*.json")):
        fday = sp.stem.replace("summary_", "")
        summary = json.loads(sp.read_text())
        fp = sdir / f"fills_{fday}.parquet"
        fills = (pl.read_parquet(fp) if fp.exists()
                 else pl.DataFrame(schema={"is_liquidation": pl.Boolean}))
        rows.append({"funding_day": fday, **attribution_for_day(fills, summary)})
    return pl.DataFrame(rows).sort("funding_day")


def _fmt(x: float, nd: int = 2) -> str:
    return "--" if not np.isfinite(x) else f"{x:,.{nd}f}"


def write_headline_table(path: Path, panel: pl.DataFrame,
                         daily: dict[int, np.ndarray], n_boot: int) -> None:
    lines = [
        r"% generated by analysis_pnl.py",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"Strategy & Total P\&L & Sharpe & 95\% CI & Max DD & Fills/day & $\overline{|q|}$ \\",
        r"\midrule",
    ]
    for sid, x in daily.items():
        ci = block_bootstrap_ci(x, sharpe_ratio, n_boot=n_boot, seed=sid)
        sub = panel.filter(pl.col("strategy") == sid)
        lines.append(
            f"{STRATEGY_LABELS.get(sid, sid)} & {_fmt(float(x.sum()), 0)} & "
            f"{_fmt(ci.point)} & [{_fmt(ci.lo)}, {_fmt(ci.hi)}] & "
            f"{_fmt(max_drawdown(x), 0)} & "
            f"{_fmt(float(sub['n_fills'].mean()), 0)} & "
            f"{_fmt(float(sub['mean_abs_inv'].mean()))} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")


def write_pairwise_table(path: Path, daily: dict[int, np.ndarray],
                         n_boot: int) -> pl.DataFrame:
    pairs = [(a, b) for a, b in KEY_PAIRS if a in daily and b in daily]
    recs = []
    for a, b in pairs:
        jkm = sharpe_ratio_test(daily[b], daily[a])   # b minus a orientation
        ci = block_bootstrap_diff_ci(daily[b], daily[a], sharpe_ratio,
                                     n_boot=n_boot, seed=100 + a * 10 + b)
        recs.append({"pair": f"{b} vs {a}", "a": a, "b": b,
                     "sharpe_diff": ci.point, "ci_lo": ci.lo, "ci_hi": ci.hi,
                     "jkm_z": jkm.z_statistic, "p": jkm.p_value})
    if not recs:
        return pl.DataFrame()
    df = pl.DataFrame(recs)
    _, adj = benjamini_hochberg(df["p"].to_numpy())
    df = df.with_columns(pl.Series("p_bh", adj))
    lines = [
        r"% generated by analysis_pnl.py",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Contrast & $\Delta$Sharpe & 95\% CI (paired bootstrap) & JKM $z$ & $p$ (BH) \\",
        r"\midrule",
    ]
    for r in df.iter_rows(named=True):
        lines.append(
            f"{STRATEGY_LABELS[r['b']]} vs {STRATEGY_LABELS[r['a']]} & "
            f"{_fmt(r['sharpe_diff'])} & [{_fmt(r['ci_lo'])}, {_fmt(r['ci_hi'])}] & "
            f"{_fmt(r['jkm_z'])} & {_fmt(r['p_bh'], 3)} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")
    return df


def write_interaction_table(path: Path, daily: dict[int, np.ndarray],
                            n_boot: int):
    a1, a0, b1, b0 = INTERACTION_SPEC
    if not all(s in daily for s in (a1, a0, b1, b0)):
        return None
    res = block_bootstrap_interaction_ci(
        daily[a1], daily[a0], daily[b1], daily[b0],
        stat_fn=sharpe_ratio, n_boot=n_boot, seed=2_654_321)
    ci_t = block_bootstrap_diff_ci(daily[a1], daily[a0], sharpe_ratio,
                                   n_boot=n_boot, seed=100 + a0 * 10 + a1)
    ci_c = block_bootstrap_diff_ci(daily[b1], daily[b0], sharpe_ratio,
                                   n_boot=n_boot, seed=100 + b0 * 10 + b1)
    p_t = sharpe_ratio_test(daily[a1], daily[a0]).p_value
    p_c = sharpe_ratio_test(daily[b1], daily[b0]).p_value
    lines = [
        r"% generated by analysis_pnl.py: complementarity (DiD) interaction",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Quantity & $\Delta$Sharpe & 95\% CI & $p$ \\",
        r"\midrule",
        f"ML effect, funding present ($S_{a1}-S_{a0}$) & "
        f"{_fmt(res.eff_treated)} & [{_fmt(ci_t.lo)}, {_fmt(ci_t.hi)}] & "
        f"{_fmt(p_t, 3)} \\\\",
        f"ML effect, funding absent ($S_{b1}-S_{b0}$) & "
        f"{_fmt(res.eff_control)} & [{_fmt(ci_c.lo)}, {_fmt(ci_c.hi)}] & "
        f"{_fmt(p_c, 3)} \\\\",
        r"\midrule",
        f"Interaction $\\delta$ (super-additivity) & {_fmt(res.point)} & "
        f"[{_fmt(res.lo)}, {_fmt(res.hi)}] & {_fmt(res.p_value, 3)} \\\\",
        r"\bottomrule", r"\end{tabular}",
    ]
    path.write_text("\n".join(lines) + "\n")
    return res


ATTR_COLS = ["spread_capture", "adverse_selection_5s", "funding", "fees",
             "inventory_residual"]
ATTR_LABELS = {
    "spread_capture": "Spread capture",
    "adverse_selection_5s": "Adverse selection (5 s)",
    "funding": "Funding fees",
    "fees": "Exchange fees",
    "inventory_residual": "Inventory residual",
}


def write_attribution_table(path: Path, attr: pl.DataFrame) -> None:
    lines = [
        r"% generated by analysis_pnl.py: strategy 6 P\&L attribution",
        r"\begin{tabular}{lrrr}",
        r"\toprule",
        r"Component & Mean / day & SD / day & Total \\",
        r"\midrule",
    ]
    for c in ATTR_COLS:
        x = attr[c].to_numpy()
        lines.append(f"{ATTR_LABELS[c]} & {_fmt(float(x.mean()))} & "
                     f"{_fmt(float(x.std(ddof=1)) if x.size > 1 else 0.0)} & "
                     f"{_fmt(float(x.sum()), 0)} \\\\")
    t = attr["terminal"].to_numpy()
    lines += [r"\midrule",
              f"Terminal P\\&L & {_fmt(float(t.mean()))} & "
              f"{_fmt(float(t.std(ddof=1)) if t.size > 1 else 0.0)} & "
              f"{_fmt(float(t.sum()), 0)} \\\\",
              r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")


def fig_cum_pnl(path: Path, days: list[str], daily: dict[int, np.ndarray]) -> None:
    fig, ax = plt.subplots(figsize=(9, 4.5))
    x = np.arange(len(days))
    for sid, v in daily.items():
        ax.plot(x, np.cumsum(v), label=STRATEGY_LABELS.get(sid, sid),
                lw=1.8 if sid == 6 else 1.0)
    step = max(1, len(days) // 8)
    ax.set_xticks(x[::step], [d[5:] for d in days[::step]], rotation=45)
    ax.set_ylabel("Cumulative P&L (USDT)")
    ax.legend(ncol=3, fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def fig_drawdown(path: Path, days: list[str], daily: dict[int, np.ndarray]) -> None:
    fig, ax = plt.subplots(figsize=(9, 3.2))
    x = np.arange(len(days))
    for sid, v in daily.items():
        cum = np.cumsum(v)
        dd = np.maximum.accumulate(cum) - cum
        ax.plot(x, -dd, label=STRATEGY_LABELS.get(sid, sid),
                lw=1.8 if sid == 6 else 1.0)
    step = max(1, len(days) // 8)
    ax.set_xticks(x[::step], [d[5:] for d in days[::step]], rotation=45)
    ax.set_ylabel("Drawdown (USDT)")
    ax.legend(ncol=3, fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def fig_attribution(path: Path, attr: pl.DataFrame) -> None:
    plt.rcParams.update({"font.size": 9, "axes.labelsize": 9,
                         "xtick.labelsize": 8, "ytick.labelsize": 8,
                         "legend.fontsize": 8})
    days = attr["funding_day"].to_list()
    x = np.arange(len(days))
    fig, ax = plt.subplots(figsize=(4.9, 3.0))
    bottom_pos = np.zeros(len(days))
    bottom_neg = np.zeros(len(days))
    draw_cols = [c for c in ATTR_COLS
                 if c != "funding" or attr["funding"].abs().max() > 5.0]
    colors = plt.cm.tab10(np.linspace(0, 1, len(ATTR_COLS)))
    for c, col in zip(ATTR_COLS, colors):
        if c not in draw_cols:
            continue
        v = attr[c].to_numpy()
        pos = np.where(v > 0, v, 0.0)
        neg = np.where(v < 0, v, 0.0)
        ax.bar(x, pos, bottom=bottom_pos, color=col, width=0.9,
               label=ATTR_LABELS[c])
        ax.bar(x, neg, bottom=bottom_neg, color=col, width=0.9)
        bottom_pos += pos
        bottom_neg += neg
    ax.plot(x, attr["terminal"].to_numpy(), "k.-", ms=3, lw=0.8,
            label="Terminal P&L")
    step = max(1, len(days) // 8)
    ax.set_xticks(x[::step], [d[5:] for d in days[::step]], rotation=45)
    ax.set_ylabel("USDT / day")
    ax.legend(ncol=3, loc="lower left", bbox_to_anchor=(0.0, 1.0, 1.0, 0.08),
              frameon=False, handlelength=1.2, columnspacing=0.8)
    ax.grid(alpha=0.3, axis="y")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def run(run_dir: Path, report_dir: Path, attribution_sid: int = 6,
        n_boot: int = 10_000) -> dict:
    report_dir.mkdir(parents=True, exist_ok=True)
    figdir = report_dir / "figures"
    figdir.mkdir(exist_ok=True)

    panel = load_daily_panel(run_dir)
    days, daily = daily_pnl_matrix(panel)
    panel.write_parquet(report_dir / "ablation_daily_pnl.parquet")

    write_headline_table(report_dir / "tab_ablation_headline.tex",
                         panel, daily, n_boot)
    pw = write_pairwise_table(report_dir / "tab_ablation_pairwise.tex",
                              daily, n_boot)
    inter = write_interaction_table(
        report_dir / "tab_ablation_interaction.tex", daily, n_boot)
    fig_cum_pnl(figdir / "fig_cum_pnl.pdf", days, daily)
    fig_drawdown(figdir / "fig_drawdown.pdf", days, daily)

    out = {"days": len(days),
           "sharpe": {s: sharpe_ratio(v) for s, v in daily.items()}}
    if attribution_sid in daily:
        attr = load_attribution(run_dir, attribution_sid)
        attr.write_parquet(report_dir / "pnl_attribution_s6.parquet")
        write_attribution_table(report_dir / "tab_pnl_attribution.tex", attr)
        fig_attribution(figdir / "fig_pnl_attribution.pdf", attr)
        resid = attr["inventory_residual"].to_numpy()
        term = attr["terminal"].to_numpy()
        out["attribution_residual_share"] = float(
            np.abs(resid).sum() / max(np.abs(term).sum(), 1e-12))
    if pw.height:
        out["pairwise"] = pw.to_dicts()
    if inter is not None:
        out["interaction"] = {
            "delta": inter.point, "ci_lo": inter.lo, "ci_hi": inter.hi,
            "p": inter.p_value, "eff_treated": inter.eff_treated,
            "eff_control": inter.eff_control}
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description="Ablation P&L analysis.")
    ap.add_argument("--run-dir", type=Path, default=Path("runs/ablation"))
    ap.add_argument("--report-dir", type=Path, default=Path("reports/ablation"))
    ap.add_argument("--n-boot", type=int, default=10_000)
    ap.add_argument("--attribution-strategy", type=int, default=6)
    args = ap.parse_args()
    out = run(args.run_dir, args.report_dir, args.attribution_strategy,
              args.n_boot)
    print(json.dumps(out, indent=2, default=str))


if __name__ == "__main__":
    main()
