"""The publication-clock placement arm."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import polars as pl

RUN_ROOT_DEFAULT = Path(
    "/mnt/rowan_thuis/Crypto_recorder/Merged_new/btcusdt/runs/rerun_20260807_ar")
BASE_CELL = "ablation_h10_qa"
FRESH_CELL = "ablation_h10_qa_freshbook"

ROWS: tuple[tuple[str, str, int], ...] = (
    (r"1 Naive (matched)", "_naive_matched", 1),
    (r"2 GLT", "", 2),
    (r"3 GLT $+$ AR", "", 3),
    (r"6 Full hybrid (horizon)", "", 6),
    (r"6 Full hybrid (defensive)", "_defensive", 6),
)
MAKER_FEE_BP = 2.0
LOT = 0.005  # BTC per lot; mean_abs_inv is recorded in BTC

ALL_ROWS: tuple[tuple[str, str, int], ...] = (
    (r"1 Naive (matched)", "_naive_matched", 1),
    (r"2 GLT", "", 2),
    (r"3 GLT $+$ AR", "", 3),
    (r"4 GLT $+$ ML", "", 4),
    (r"5 GLT $+$ funding", "", 5),
    (r"6 Full hybrid", "", 6),
    (r"3 GLT $+$ AR (def.)", "_defensive", 3),
    (r"4 GLT $+$ ML (def.)", "_defensive", 4),
    (r"6 Full hybrid (def.)", "_defensive", 6),
)


def _day_stats(sdir: Path, day: str) -> dict:
    """One day, one strategy: P&L, fills, and the per-fill bps decomposition."""
    summary = json.loads((sdir / f"summary_{day}.json").read_text())
    f = pl.read_parquet(sdir / f"fills_{day}.parquet").filter(
        ~pl.col("is_liquidation"))
    px = f["price"].to_numpy()
    side = f["side"].to_numpy().astype(float)
    m0, m5 = f["mid_0s"].to_numpy(), f["mid_5s"].to_numpy()
    ok = np.isfinite(m0) & np.isfinite(m5)
    cap = 1e4 * (side * (m0 - px) / px)[ok]
    adv = 1e4 * (side * (m5 - m0) / px)[ok]
    return {
        "day": day,
        "pnl": float(summary["terminal_pnl"]),
        "n_fills": int(summary["n_fills"]),
        "maker_fee": float(f["fee"].sum()),
        "mean_abs_inv": float(summary["mean_abs_inv"]),
        "frac_cap": float(summary["frac_time_at_cap"]),
        "notional": float((f["price"] * f["qty"]).sum()),
        "capture": cap, "advsel": adv, "markout": cap + adv,
        "cap_d": float(cap.mean()), "adv_d": float(adv.mean()),
        "mo_d": float((cap + adv).mean()),
    }


def cell_stats(run_root: Path, cell: str, sid: int) -> dict:
    sdir = run_root / cell / f"s{sid}"
    days = sorted(p.stem.replace("summary_", "")
                  for p in sdir.glob("summary_*.json"))
    if not days:
        raise FileNotFoundError(f"no summaries under {sdir}")
    d = [_day_stats(sdir, day) for day in days]
    pnl = np.array([x["pnl"] for x in d])
    fee = np.array([x["maker_fee"] for x in d])
    ntl = np.array([x["notional"] for x in d])
    pool = {k: np.concatenate([x[k] for x in d])
            for k in ("capture", "advsel", "markout")}
    return {
        "days": [x["day"] for x in d], "n_days": len(d),
        "pnl_day": float(pnl.mean()), "fills_day": float(np.mean([x["n_fills"] for x in d])),
        "capture": float(pool["capture"].mean()),
        "advsel": float(pool["advsel"].mean()),
        "markout": float(pool["markout"].mean()),
        # break-even maker fee: where mean daily P&L crosses zero
        "mstar_bp": float(1e4 * (pnl.mean() + fee.mean()) / ntl.mean()),
        "pnl_zero_fee": float((pnl + fee).mean()),
        "sd": float(pnl.std(ddof=1)),
        "sharpe": float(pnl.mean() / pnl.std(ddof=1) * np.sqrt(365.0)),
        "es5": float(np.sort(pnl)[:max(1, int(round(0.05 * len(pnl))))].mean()),
        "inv_lots": float(np.mean([x["mean_abs_inv"] for x in d]) / LOT),
        "cap_pct": float(100.0 * np.mean([x["frac_cap"] for x in d])),
        # daily series, for the paired tests
        "_pnl": pnl,
        "_mo": np.array([x["mo_d"] for x in d]),
        "_cap": np.array([x["cap_d"] for x in d]),
        "_adv": np.array([x["adv_d"] for x in d]),
    }


def paired(a: dict, b: dict, key: str) -> dict:
    """b minus a on the common days; Student t on the daily differences."""
    ia = {d: i for i, d in enumerate(a["days"])}
    common = [d for d in b["days"] if d in ia]
    x = np.array([a[key][ia[d]] for d in common])
    y = np.array([b[key][b["days"].index(d)] for d in common])
    diff = y - x
    sd = diff.std(ddof=1)
    return {"mean": float(diff.mean()), "n": len(diff),
            "t": float(diff.mean() / (sd / np.sqrt(len(diff)))) if sd > 0 else float("nan")}


def _fmt(x: float, nd: int = 2) -> str:
    return "--" if not np.isfinite(x) else f"{x:,.{nd}f}"


def write_tex(path: Path, res: dict) -> None:
    """Publication-clock rows only. The deployed counterparts are already in
    Tables tab:results_main and tab:results_couplings, and every contrast that
    matters is quoted in the text, so tabulating both clocks would duplicate a
    page of numbers the reader has seen."""
    lines = [
        r"% generated by analysis_freshbook.py",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        (r"Strategy & P\&L/day & Fills/day & Capture & Adv.\ sel.\ & "
         r"Markout & $m^*$ \\"),
        (r" & (USDT) &  & (bps) & (bps) & (bps) & (bp) \\"),
        r"\midrule",
    ]
    for label, _suffix, _sid in ROWS:
        r = res[label]["fresh"]
        lines.append(
            f"{label} & {_fmt(r['pnl_day'], 0)} & "
            f"{_fmt(r['fills_day'], 0)} & {_fmt(r['capture'], 3)} & "
            f"{_fmt(r['advsel'], 3)} & {_fmt(r['markout'], 3)} & "
            f"{_fmt(r['mstar_bp'], 2)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")


def write_tex_full(path: Path, res: dict) -> None:
    """The complete record, both clocks, for the appendix."""
    lines = [
        r"% generated by analysis_freshbook.py",
        r"\begin{tabular}{llrrrrrrrrr}",
        r"\toprule",
        (r"Strategy & Clock & P\&L/day & SD & Sharpe & ES$_{5\%}$ & Fills/day & "
         r"$\overline{|q|}$ & Capture & Adv.\ sel.\ & Markout \\"),
        (r" &  & (USDT) & (USDT) &  & (USDT) &  & (lots) & (bps) & (bps) & (bps) \\"),
        r"\midrule",
    ]
    for label, _suffix, _sid in ALL_ROWS:
        for clock, tag in (("deployed", "deployed"), ("publication", "fresh")):
            r = res[label][tag]
            lines.append(
                f"{label if clock == 'deployed' else ''} & {clock} & "
                f"{_fmt(r['pnl_day'], 0)} & {_fmt(r['sd'], 0)} & "
                f"{_fmt(r['sharpe'], 1)} & {_fmt(r['es5'], 0)} & "
                f"{_fmt(r['fills_day'], 0)} & {_fmt(r['inv_lots'], 2)} & "
                f"{_fmt(r['capture'], 3)} & {_fmt(r['advsel'], 3)} & "
                f"{_fmt(r['markout'], 3)} \\\\")
        lines.append(r"\addlinespace")
    lines = lines[:-1] + [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")


def run(run_root: Path, report_dir: Path) -> dict:
    report_dir.mkdir(parents=True, exist_ok=True)
    res: dict = {}
    for label, suffix, sid in dict.fromkeys(ROWS + ALL_ROWS):
        res[label] = {
            "deployed": cell_stats(run_root, BASE_CELL + suffix, sid),
            "fresh": cell_stats(run_root, FRESH_CELL + suffix, sid),
        }
    write_tex(report_dir / "tab_freshbook.tex", res)
    write_tex_full(report_dir / "tab_freshbook_full.tex", res)

    tests: dict = {"fresh_minus_deployed": {}, "vs_glt": {"deployed": {}, "fresh": {}}}
    for label, _s, _i in ROWS:
        tests["fresh_minus_deployed"][label] = {
            k: paired(res[label]["deployed"], res[label]["fresh"], f"_{k}")
            for k in ("pnl", "mo", "cap", "adv")}
    glt = res[r"2 GLT"]
    for clock in ("deployed", "fresh"):
        for label, _s, _i in ROWS:
            if label == r"2 GLT":
                continue
            tests["vs_glt"][clock][label] = {
                k: paired(glt[clock], res[label][clock], f"_{k}")
                for k in ("mo", "cap", "adv")}

    depth: dict = {}
    for clock in ("deployed", "fresh"):
        labs = [lab for lab, _s, _i in ROWS]
        days = sorted(set.intersection(*[set(res[l][clock]["days"]) for l in labs]))
        idx = {l: {d: i for i, d in enumerate(res[l][clock]["days"])} for l in labs}
        cap = np.array([[res[l][clock]["_cap"][idx[l][d]] for l in labs] for d in days])
        mo = np.array([[res[l][clock]["_mo"][idx[l][d]] for l in labs] for d in days])
        resid = np.empty_like(mo)
        slope = np.empty(len(days))
        for i in range(len(days)):
            x, y = cap[i], mo[i]
            b = ((x - x.mean()) * (y - y.mean())).sum() / ((x - x.mean()) ** 2).sum()
            slope[i] = b
            resid[i] = y - (y.mean() + b * (x - x.mean()))
        cm, mm = cap.mean(0), mo.mean(0)
        b = ((cm - cm.mean()) * (mm - mm.mean())).sum() / ((cm - cm.mean()) ** 2).sum()
        pred = mm.mean() + b * (cm - cm.mean())
        depth[clock] = {
            "slope": float(slope.mean()),
            "slope_t": float(slope.mean() / (slope.std(ddof=1) / np.sqrt(len(days)))),
            "r2_of_means": float(1 - ((mm - pred) ** 2).sum() / ((mm - mm.mean()) ** 2).sum()),
            "residual": {l: {"mean": float(resid[:, j].mean()),
                             "t": float(resid[:, j].mean()
                                        / (resid[:, j].std(ddof=1) / np.sqrt(len(days))))}
                         for j, l in enumerate(labs)},
            "residual_spread": float(resid.mean(0).max() - resid.mean(0).min()),
            "markout_spread": float(mm.max() - mm.min()),
        }

    split: dict = {}
    for label, _s, _i in ROWS:
        a, b = res[label]["deployed"], res[label]["fresh"]
        gain = b["pnl_day"] - a["pnl_day"]
        part = (b["fills_day"] - a["fills_day"]) * (a["pnl_day"] / a["fills_day"])
        split[label] = {"gain": gain, "participation": part,
                        "participation_share": part / gain if gain else float("nan"),
                        "quality": gain - part}

    out = {"run_root": str(run_root),
           "table": {lab: {c: {k: v for k, v in r.items() if not k.startswith("_")}
                           for c, r in d.items()} for lab, d in res.items()},
           "tests": tests, "participation_split": split,
           "depth_control": depth}
    (report_dir / "freshbook.json").write_text(json.dumps(out, indent=1))
    return out


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run-root", type=Path, default=RUN_ROOT_DEFAULT)
    ap.add_argument("--report-dir", type=Path,
                    default=Path("reports/rerun_20260807_ar/freshbook"))
    a = ap.parse_args()
    out = run(a.run_root, a.report_dir)
    for label, _s, _i in ROWS:
        d, f = out["table"][label]["deployed"], out["table"][label]["fresh"]
        sp = out["participation_split"][label]
        print(f"{label:28s} {d['pnl_day']:8.1f} -> {f['pnl_day']:8.1f}  "
              f"markout {d['markout']:+.3f} -> {f['markout']:+.3f}  "
              f"m* {d['mstar_bp']:+.2f} -> {f['mstar_bp']:+.2f}  "
              f"participation {sp['participation_share']:.0%}")
    print(f"\nwrote {a.report_dir}/tab_freshbook.tex")


if __name__ == "__main__":
    main()
