"""Post-trade markout at 1 s, 5 s and 30 s."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import polars as pl

from statistical_tests import (
    benjamini_hochberg,
    block_bootstrap_ci,
    mann_whitney_test,
    ppw_block_length,
)

HORIZONS = (1, 5, 30)
BASELINE_SID = 2
STRATEGY_LABELS = {
    1: "1 Naive", 2: "2 GLT", 3: "3 GLT+AR",
    4: "4 GLT+ML", 5: "5 GLT+Fund", 6: "6 Full hybrid",
}
# time-to-funding buckets (seconds), nearest-settlement first
U_BUCKETS = [(0, 60), (60, 300), (300, 900), (900, 1800), (1800, 28_800)]
U_BUCKET_LABELS = ["<1m", "1-5m", "5-15m", "15-30m", ">30m"]


def load_fills(run_dir: Path) -> pl.DataFrame:
    """All maker fills across strategies/days with markout columns in bps."""
    frames = []
    for sdir in sorted(run_dir.glob("s[0-9]")):
        for fp in sorted(sdir.glob("fills_*.parquet")):
            df = pl.read_parquet(fp)
            if df.height == 0:
                continue
            frames.append(df.with_columns(
                pl.lit(fp.stem.replace("fills_", "")).alias("funding_day")))
    if not frames:
        raise FileNotFoundError(f"no fills under {run_dir}/s*/")
    fills = pl.concat(frames, how="vertical_relaxed").filter(
        ~pl.col("is_liquidation"))
    cols = [
        (pl.col("side") * (pl.col(f"mid_{tau}s") - pl.col("price"))
         / pl.col("price") * 1e4).alias(f"mo_{tau}s")
        for tau in HORIZONS
    ]
    return fills.with_columns(cols)


def join_funding_sign(fills: pl.DataFrame, base: Path) -> pl.DataFrame:
    """Backward as-of join of the (forward-filled, exogenous) funding rate at
    fill time, drives the sign-of-carry stratification."""
    from pipeline_utils import funding_day_paths

    out = []
    for fday, grp in fills.group_by("funding_day", maintain_order=True):
        fday = fday[0] if isinstance(fday, tuple) else fday
        frames = []
        for d, h in funding_day_paths(base, str(fday)):
            p = base / d / f"markprice_ffill_{h:02d}h.parquet"
            if p.exists():
                frames.append(pl.read_parquet(p, columns=["ts_ms", "FundingRate"]))
        if not frames:
            out.append(grp.with_columns(pl.lit(None, pl.Float64)
                                        .alias("funding_rate")))
            continue
        mk = pl.concat(frames).sort("ts_ms").rename(
            {"FundingRate": "funding_rate"})
        out.append(grp.sort("ts_ms").join_asof(mk, on="ts_ms",
                                               strategy="backward"))
    return pl.concat(out, how="vertical_relaxed")


def _fmt(x, nd=2) -> str:
    return "--" if x is None or not np.isfinite(x) else f"{x:,.{nd}f}"


def distribution_table(fills: pl.DataFrame, path: Path,
                       n_boot: int = 2000) -> pl.DataFrame:
    recs = []
    for sid in sorted(fills["strategy"].unique().to_list()):
        sub = fills.filter(pl.col("strategy") == sid).sort("ts_ms")
        ts = sub["ts_ms"].to_numpy()
        gaps = np.diff(ts)
        med_gap_s = float(np.median(gaps)) / 1e3 if gaps.size else float("nan")
        for tau in HORIZONS:
            x = sub[f"mo_{tau}s"].drop_nulls().drop_nans().to_numpy()
            if x.size == 0:
                continue
            bl = ppw_block_length(x)
            ci = block_bootstrap_ci(x, lambda v: float(np.mean(v)),
                                    n_boot=n_boot, block_len=bl, seed=sid)
            recs.append({
                "strategy": sid, "tau": tau, "n": x.size,
                "mean": float(x.mean()), "mean_lo": ci.lo, "mean_hi": ci.hi,
                "median": float(np.median(x)),
                "p5": float(np.quantile(x, 0.05)),
                "p95": float(np.quantile(x, 0.95)),
                "block_len": float(bl),
                "fills_per_tau": float(tau / med_gap_s) if med_gap_s and np.isfinite(med_gap_s) else float("nan"),
            })
    df = pl.DataFrame(recs)
    lines = [r"% generated by analysis_markout.py",
             r"\begin{tabular}{llrrrrr}", r"\toprule",
             r"Strategy & $\tau$ & $n$ & Mean [95\% CI] & Median & P5 & P95 \\",
             r"\midrule"]
    for r in df.iter_rows(named=True):
        lines.append(
            f"{STRATEGY_LABELS.get(r['strategy'], r['strategy'])} & "
            f"{r['tau']}\\,s & {r['n']:,} & "
            f"{_fmt(r['mean'])} [{_fmt(r['mean_lo'])}, {_fmt(r['mean_hi'])}] & "
            f"{_fmt(r['median'])} & {_fmt(r['p5'])} & {_fmt(r['p95'])} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")
    _write_blocklen_diagnostic(df, path.with_name("tab_markout_blocklen.tex"))
    return df


def _write_blocklen_diagnostic(df: pl.DataFrame, path: Path) -> None:
    """PPW block length per (strategy, tau) next to fills_per_tau, the count of
    active-trading fills spanning tau seconds derived from the median inter-fill
    gap. The tau-window overlap is a lower bound on the dependence."""
    if df.is_empty() or "block_len" not in df.columns:
        return
    lines = [r"% generated by analysis_markout.py (markout-CI block-length diagnostic)",
             r"\begin{tabular}{llrrr}", r"\toprule",
             r"Strategy & $\tau$ & $n$ & PPW block & Fills per $\tau$ \\",
             r"\midrule"]
    for r in df.sort(["strategy", "tau"]).iter_rows(named=True):
        lines.append(
            f"{STRATEGY_LABELS.get(r['strategy'], r['strategy'])} & "
            f"{r['tau']}\\,s & {r['n']:,} & "
            f"{_fmt(r['block_len'])} & {_fmt(r['fills_per_tau'], 0)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")
    print("markout CI block length (PPW) by (strategy, tau):")
    for r in df.sort(["strategy", "tau"]).iter_rows(named=True):
        fpt = r["fills_per_tau"]
        fpt_s = f"{fpt:,.0f}" if np.isfinite(fpt) else "n/a"
        print(f"  s{r['strategy']} tau={r['tau']:>2}s  "
              f"block={r['block_len']:8.1f}  fills/tau~{fpt_s}")


def test_table(fills: pl.DataFrame, path: Path) -> pl.DataFrame:
    base = fills.filter(pl.col("strategy") == BASELINE_SID)
    recs = []
    for sid in sorted(fills["strategy"].unique().to_list()):
        if sid == BASELINE_SID:
            continue
        sub = fills.filter(pl.col("strategy") == sid)
        for tau in HORIZONS:
            a = sub[f"mo_{tau}s"].drop_nulls().drop_nans().to_numpy()
            b = base[f"mo_{tau}s"].drop_nulls().drop_nans().to_numpy()
            if a.size < 10 or b.size < 10:
                continue
            r = mann_whitney_test(a, b, alternative="greater")
            recs.append({"strategy": sid, "tau": tau, "U": r.statistic,
                         "p": r.p_value, "rank_biserial": r.rank_biserial,
                         "n_a": r.n_a, "n_b": r.n_b})
    df = pl.DataFrame(recs)
    if df.height:
        _, adj = benjamini_hochberg(df["p"].to_numpy())
        df = df.with_columns(pl.Series("p_bh", adj))
    lines = [r"% generated by analysis_markout.py: one-sided MWU vs strategy 2",
             r"\begin{tabular}{llrrr}", r"\toprule",
             r"Strategy & $\tau$ & rank-biserial $r$ & $p$ & $p$ (BH) \\",
             r"\midrule"]
    for r in df.iter_rows(named=True):
        lines.append(
            f"{STRATEGY_LABELS.get(r['strategy'], r['strategy'])} & "
            f"{r['tau']}\\,s & {_fmt(r['rank_biserial'], 3)} & "
            f"{_fmt(r['p'], 4)} & {_fmt(r['p_bh'], 4)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")
    return df


def fig_markout_by_u(fills: pl.DataFrame, path: Path, tau: int = 5) -> pl.DataFrame:
    """Mean markout per strategy per time-to-funding bucket."""
    recs = []
    for sid in sorted(fills["strategy"].unique().to_list()):
        sub = fills.filter(pl.col("strategy") == sid)
        for (lo, hi), lab in zip(U_BUCKETS, U_BUCKET_LABELS):
            x = (sub.filter((pl.col("u_s") >= lo) & (pl.col("u_s") < hi))
                 [f"mo_{tau}s"].drop_nulls().drop_nans().to_numpy())
            if x.size:
                recs.append({"strategy": sid, "bucket": lab,
                             "mean_mo": float(x.mean()),
                             "se": float(x.std(ddof=1) / np.sqrt(x.size))
                             if x.size > 1 else 0.0,
                             "n": x.size})
    df = pl.DataFrame(recs)
    fig, ax = plt.subplots(figsize=(8, 4))
    xpos = np.arange(len(U_BUCKET_LABELS))
    for sid in sorted(set(df["strategy"].to_list())):
        sub = df.filter(pl.col("strategy") == sid)
        y = {r["bucket"]: (r["mean_mo"], r["se"]) for r in sub.iter_rows(named=True)}
        means = [y.get(lab, (np.nan, 0))[0] for lab in U_BUCKET_LABELS]
        ses = [y.get(lab, (np.nan, 0))[1] for lab in U_BUCKET_LABELS]
        ax.errorbar(xpos, means, yerr=ses, marker="o", capsize=3,
                    label=STRATEGY_LABELS.get(sid, sid),
                    lw=1.8 if sid == 6 else 1.0)
    ax.set_xticks(xpos, U_BUCKET_LABELS)
    ax.set_xlabel("time to funding settlement")
    ax.set_ylabel(f"mean markout at {tau}s (bps)")
    ax.axhline(0, color="k", lw=0.5)
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)
    return df


def fig_markout_dist(dist: pl.DataFrame, path: Path) -> None:
    fig, axes = plt.subplots(1, len(HORIZONS), figsize=(11, 3.5), sharey=True)
    for ax, tau in zip(axes, HORIZONS):
        sub = dist.filter(pl.col("tau") == tau)
        sids = sub["strategy"].to_list()
        x = np.arange(len(sids))
        med = sub["median"].to_numpy()
        p5 = sub["p5"].to_numpy()
        p95 = sub["p95"].to_numpy()
        ax.errorbar(x, med, yerr=[med - p5, p95 - med], fmt="o", capsize=4)
        ax.set_xticks(x, [str(s) for s in sids])
        ax.set_title(f"$\\tau$ = {tau}s")
        ax.axhline(0, color="k", lw=0.5)
        ax.grid(alpha=0.3)
    axes[0].set_ylabel("markout (bps), median + 5/95 pct")
    fig.tight_layout()
    fig.savefig(path)
    plt.close(fig)


def carry_sign_table(fills: pl.DataFrame, path: Path, tau: int = 5) -> pl.DataFrame:
    """Mean markout split by sign(f_t) at fill, Phi is linear in q, so the
    funding-aware edge should appear under BOTH carry signs."""
    if "funding_rate" not in fills.columns:
        return pl.DataFrame()
    recs = []
    for sid in sorted(fills["strategy"].unique().to_list()):
        sub = fills.filter(pl.col("strategy") == sid)
        for sgn, name in [(1, "positive carry"), (-1, "negative carry")]:
            x = (sub.filter(pl.col("funding_rate") * sgn > 0)
                 [f"mo_{tau}s"].drop_nulls().drop_nans().to_numpy())
            if x.size:
                recs.append({"strategy": sid, "carry": name, "n": x.size,
                             "mean_mo": float(x.mean())})
    df = pl.DataFrame(recs)
    lines = [r"% generated by analysis_markout.py: carry-sign stratification",
             r"\begin{tabular}{llrr}", r"\toprule",
             r"Strategy & Carry regime & $n$ & Mean markout (bps) \\",
             r"\midrule"]
    for r in df.iter_rows(named=True):
        lines.append(f"{STRATEGY_LABELS.get(r['strategy'], r['strategy'])} & "
                     f"{r['carry']} & {r['n']:,} & {_fmt(r['mean_mo'])} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    path.write_text("\n".join(lines) + "\n")
    return df


def run(run_dir: Path, report_dir: Path, base: Path | None = None,
        n_boot: int = 2000) -> dict:
    report_dir.mkdir(parents=True, exist_ok=True)
    figdir = report_dir / "figures"
    figdir.mkdir(exist_ok=True)

    fills = load_fills(run_dir)
    if base is not None:
        try:
            fills = join_funding_sign(fills, base)
        except Exception as e:  # carry table is optional enrichment
            print(f"WARN: funding-sign join skipped: {e}")
    fills.write_parquet(report_dir / "markout_fills.parquet")

    dist = distribution_table(fills, report_dir / "tab_markout_dist.tex",
                              n_boot=n_boot)
    tests = test_table(fills, report_dir / "tab_markout_tests.tex")
    by_u = fig_markout_by_u(fills, figdir / "fig_markout_by_u.pdf")
    by_u.write_parquet(report_dir / "markout_by_u.parquet")
    fig_markout_dist(dist, figdir / "fig_markout_dist.pdf")
    carry = (carry_sign_table(fills, report_dir / "tab_markout_carry.tex")
             if "funding_rate" in fills.columns else pl.DataFrame())

    return {"n_fills": fills.height,
            "tests": tests.to_dicts() if tests.height else [],
            "carry_rows": carry.height}


def main() -> None:
    ap = argparse.ArgumentParser(description="Adverse-selection markout analysis.")
    ap.add_argument("--run-dir", type=Path, default=Path("runs/ablation"))
    ap.add_argument("--report-dir", type=Path, default=Path("reports/ablation"))
    ap.add_argument("--base", type=Path, default=None,
                    help="dataset root for the funding-sign stratification")
    ap.add_argument("--n-boot", type=int, default=2000)
    args = ap.parse_args()
    out = run(args.run_dir, args.report_dir, args.base, args.n_boot)
    print(json.dumps({k: v for k, v in out.items() if k != "tests"}, indent=2))


if __name__ == "__main__":
    main()
