"""Inventory position at settlement, by strategy."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import polars as pl
from scipy import stats

RUN_DEFAULT = Path("/mnt/rowan_thuis/Crypto_recorder/Merged_new/btcusdt/runs/"
                   "rerun_20260807_ar/ablation_h10_qa")
STRATS = (2, 4, 5, 6)
LOT_BTC = 0.005


FLAT_USD = 1e-3
FINAL_MIN_S = 60.0


def settlements(cell: Path, sid: int) -> pl.DataFrame:
    """One record per settlement: state at the instant, and the booked charge.

    The charge is the step of `funding_cum` across the clock wrap, i.e. what the
    engine actually booked, not -q*S*f recomputed from the last grid second.
    """
    recs = []
    for p in sorted((cell / f"s{sid}").glob("pnl_*.parquet")):
        d = pl.read_parquet(p, columns=["u_s", "inv", "f_rate", "mid",
                                        "funding_cum", "paused"])
        u, inv = d["u_s"].to_numpy(), d["inv"].to_numpy()
        f, fc = d["f_rate"].to_numpy(), d["funding_cum"].to_numpy()
        paused = d["paused"].to_numpy()
        col = -(inv / LOT_BTC) * np.sign(f)
        for w in np.where(np.diff(u) > 0)[0]:
            if paused[w]:
                continue
            fin = (u[:w + 1] <= FINAL_MIN_S) & ~paused[:w + 1]
            recs.append({
                "day": p.stem.replace("pnl_", ""),
                "q_lots": inv[w] / LOT_BTC,
                "collect_lots": col[w],
                "collect_lots_final_min": float(col[:w + 1][fin].mean())
                if fin.any() else float("nan"),
                "payment_usd": float(fc[w + 1] - fc[w])})
    return pl.DataFrame(recs)


def bucket_means(cell: Path, sid: int) -> dict:
    """Seconds-weighted collecting inventory in the <1m and >30m buckets."""
    near, far = [], []
    for p in sorted((cell / f"s{sid}").glob("pnl_*.parquet")):
        d = pl.read_parquet(p, columns=["u_s", "inv", "f_rate", "paused"]
                            ).filter(~pl.col("paused"))
        u = d["u_s"].to_numpy()
        c = -(d["inv"].to_numpy() / LOT_BTC) * np.sign(d["f_rate"].to_numpy())
        near.append(c[u < FINAL_MIN_S])
        far.append(c[u >= 1800.0])
    def _mean(xs: list) -> float:
        a = np.concatenate(xs) if xs else np.array([])
        return float(a.mean()) if a.size else float("nan")
    return {"collect_lots_under_1m_secwt": _mean(near),
            "collect_lots_over_30m_secwt": _mean(far)}


def summarise(d: pl.DataFrame) -> dict:
    c, s = d["collect_lots"].to_numpy(), d["payment_usd"].to_numpy()
    return {"n": d.height,
            # booked-charge classification (matches analysis_money_figure.py)
            "collect_pct": float(100.0 * (s > FLAT_USD).mean()),
            "pay_pct": float(100.0 * (s < -FLAT_USD).mean()),
            "flat_pct": float(100.0 * (np.abs(s) <= FLAT_USD).mean()),
            # positioning (carry-independent; what the correction controls)
            "pct_inv_on_collecting_side": float(100.0 * (c > 0).mean()),
            "mean_collect_lots": float(c.mean()),
            "mean_collect_lots_final_min": float(
                np.nanmean(d["collect_lots_final_min"].to_numpy())),
            "mean_abs_q_lots": float(np.abs(d["q_lots"].to_numpy()).mean()),
            "mean_payment_usd": float(s.mean()),
            "total_payment_usd": float(s.sum())}


def paired(a: np.ndarray, b: np.ndarray) -> dict:
    diff = b - a
    t, p = stats.ttest_rel(b, a)
    return {"diff": float(diff.mean()),
            "se": float(diff.std(ddof=1) / np.sqrt(len(diff))),
            "t": float(t), "p": float(p), "n": len(diff)}


def analyse(cell: Path) -> dict:
    d = {s: settlements(cell, s) for s in STRATS}
    n = min(x.height for x in d.values())
    col = {s: d[s]["collect_lots"].to_numpy()[:n] for s in STRATS}
    pay = {s: d[s]["payment_usd"].to_numpy()[:n] for s in STRATS}

    res = {"run": str(cell), "n_settlements": n,
           "per_strategy": {f"s{s}": {**summarise(d[s]), **bucket_means(cell, s)}
                            for s in STRATS},
           "contrasts": {
               "funding_alone_s5_vs_s2": paired(col[2], col[5]),
               "funding_on_ml_s6_vs_s4": paired(col[4], col[6]),
               "ml_alone_s4_vs_s2": paired(col[2], col[4]),
               "ml_on_correction_s6_vs_s5": paired(col[5], col[6])},
           "payment_contrasts": {
               "funding_alone_s5_vs_s2": paired(pay[2], pay[5]),
               "ml_on_correction_s6_vs_s5": paired(pay[5], pay[6])}}
    # interaction: what ML does to the correction, vs what it does to baseline
    res["interaction_did_lots"] = paired(col[4] - col[2], col[6] - col[5])
    res["interaction_did_usd"] = paired(pay[4] - pay[2], pay[6] - pay[5])
    return res


def write_tex(res: dict, path: Path) -> None:
    lines = ["% generated by analysis_funding_inventory.py",
             r"\begin{tabular}{lrrrr}", r"\toprule",
             (r"Strategy & On collecting side (\%) & Collect.\ inv.\ (lots) & "
              r"$|q|$ (lots) & Payment (USD) \\"), r"\midrule"]
    name = {2: "2 GLT", 4: r"4 GLT $+$ ML", 5: r"5 GLT $+$ funding",
            6: "6 Full hybrid"}
    for s in STRATS:
        v = res["per_strategy"][f"s{s}"]
        lines.append(f"{name[s]} & {v["pct_inv_on_collecting_side"]:.1f} & "
                     f"{v['mean_collect_lots']:+.3f} & "
                     f"{v['mean_abs_q_lots']:.2f} & "
                     f"{v['mean_payment_usd']:+.4f} \\\\")
    d = res["interaction_did_lots"]
    lines += [r"\midrule",
              (r"\multicolumn{5}{l}{Interaction (6$-$5)$-$(4$-$2): "
               f"{d['diff']:+.3f} lots, $t={d['t']:+.2f}$, $p={d['p']:.3f}$}}"
               r" \\"),
              r"\bottomrule", r"\end{tabular}", ""]
    path.write_text("\n".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run", type=Path, default=RUN_DEFAULT)
    ap.add_argument("--report-dir", type=Path,
                    default=Path("reports/rerun_20260807_ar/funding_inventory"))
    args = ap.parse_args()
    res = analyse(args.run)
    args.report_dir.mkdir(parents=True, exist_ok=True)
    (args.report_dir / "funding_inventory.json").write_text(json.dumps(res, indent=1))
    write_tex(res, args.report_dir / "tab_funding_inventory.tex")
    for s in STRATS:
        v = res["per_strategy"][f"s{s}"]
        print(f"s{s}: collect {v['collect_pct']:5.1f}%  pay {v['pay_pct']:5.1f}%"
              f"  flat {v['flat_pct']:4.1f}%  | inv-side {v['pct_inv_on_collecting_side']:5.1f}%"
              f"  collect {v['mean_collect_lots']:+.2f} lots  <1m "
              f"{v['collect_lots_under_1m_secwt']:+.2f}  >30m "
              f"{v['collect_lots_over_30m_secwt']:+.2f}  |q| {v['mean_abs_q_lots']:.2f}"
              f"  total {v['total_payment_usd']:+.2f} USD")
    for k in ("funding_alone_s5_vs_s2", "ml_alone_s4_vs_s2",
              "ml_on_correction_s6_vs_s5"):
        v = res["contrasts"][k]
        print(f"  {k:<28} {v['diff']:+.3f} lots  t={v['t']:+5.2f}  p={v['p']:.4f}")
    d = res["interaction_did_lots"]
    print(f"  INTERACTION (6-5)-(4-2)      {d['diff']:+.3f} lots  "
          f"t={d['t']:+5.2f}  p={d['p']:.4f}  (n={d['n']})")
    print("written:", args.report_dir)


if __name__ == "__main__":
    main()
