"""Census of the Regime-II switch time at every settlement."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import polars as pl

from analysis_funding_activation import (
    BASE_DEFAULT,
    EPOCH_S_DEFAULT,
    GAMMA_DEFAULT,
    Q_DEFAULT,
    RHO_DEFAULT,
    SIGMA_COL_DEFAULT,
    census_day,
)

RUN_DIR_DEFAULT = Path("/mnt/rowan_thuis/Crypto_recorder/Merged_new/btcusdt/"
                       "runs/rerun_20260807_ar/ablation_h10_qa")
STRATEGY_DEFAULT = "s5"
U_MAX_FLOOR_S = 1800.0   # LUT-horizon floor the sim gates with, for the figure
U_MAX_CAP_S = 7200.0


def observed_switches(
    pnl: pl.DataFrame, settlements: list[int]
) -> dict[int, float]:
    """Realised Regime-II switch lead time (seconds before settlement) per
    settlement, from one day's 1 s pnl snapshots.

    Within the epoch leading up to settlement t, the first tick with regime == 2
    carries the largest u_s, because u_s decreases monotonically and the regime
    latches once u_s <= u*. That max u_s is the lead time. Epochs with no
    regime==2 tick are recorded as 0.0."""
    cands = sorted(settlements)
    r2 = pnl.filter(pl.col("regime") == 2).select("ts_ms", "u_s")
    out: dict[int, float] = {}
    lo = -(1 << 62)
    for t in cands:
        hi = t
        seg = r2.filter((pl.col("ts_ms") > lo) & (pl.col("ts_ms") <= hi))
        out[t] = float(seg["u_s"].max()) if seg.height else 0.0
        lo = t
    return out


def _stats(x: np.ndarray) -> dict:
    if x.size == 0:
        return {"n": 0, "min": 0.0, "max": 0.0, "median": 0.0, "mean": 0.0}
    return {
        "n": int(x.size),
        "min": float(np.min(x)),
        "max": float(np.max(x)),
        "median": float(np.median(x)),
        "mean": float(np.mean(x)),
    }


def aggregate(records: list[dict]) -> dict:
    """Switch-length + F_t summaries. Length stats are over settlements where
    the layer actually switched on (u_switch_s > 0); the switching fraction is
    reported alongside so the conditional stats are not mistaken for
    unconditional ones."""
    if not records:
        return {"n": 0}
    us = np.array([r["u_switch_s"] for r in records])
    uh = np.array([r["u_hat_s"] for r in records])
    Ft = np.array([r["F_t"] for r in records])
    formed = us > 0.0
    return {
        "n": len(records),
        "frac_layer_switches": float(formed.mean()),
        "u_switch_s": _stats(us[formed]),        # conditional on switching on
        "u_hat_s": _stats(uh[formed]),
        "F_t_abs_median": float(np.median(np.abs(Ft))),
        "F_t_abs_mean": float(np.mean(np.abs(Ft))),
        "F_t_signed_median": float(np.median(Ft)),
        "F_t_signed_mean": float(np.mean(Ft)),
    }


def write_tex(aggs: dict[str, dict], path: Path, params: dict) -> None:
    cols = [(h, aggs[k]) for h, k in
            [("Pre-analysis", "pre_analysis"), ("Out-of-sample", "sim")]
            if aggs[k].get("n")]
    if len(cols) > 1:
        cols.append(("All", aggs["all"]))
    if not cols:
        cols = [("All", aggs["all"])]

    def row(label: str, getter, fmt: str = ".0f") -> str:
        def cell(a: dict) -> str:
            return f"{getter(a):{fmt}}" if a.get("n") else "--"
        cells = " & ".join(cell(a) for _, a in cols)
        return f"{label} & {cells} \\\\"

    ncol = len(cols) + 1
    us = lambda a: a["u_switch_s"]  # noqa: E731
    lines = [
        "% Auto-generated by analysis_boundary_layer.py, do not edit.",
        "\\begin{tabular}{l" + "r" * len(cols) + "}",
        "\\toprule",
        " & " + " & ".join(h for h, _ in cols) + " \\\\",
        "\\midrule",
        row("Settlements", lambda a: a["n"]),
        row("Layer switches on (\\%)",
            lambda a: 100.0 * a["frac_layer_switches"], ".1f"),
        "\\midrule",
        f"\\multicolumn{{{ncol}}}{{l}}{{\\emph{{Regime-II switch lead $u^*$ "
        "(s), switching settlements}} \\\\",
        row("\\quad min", lambda a: us(a)["min"]),
        row("\\quad median", lambda a: us(a)["median"]),
        row("\\quad mean", lambda a: us(a)["mean"]),
        row("\\quad max", lambda a: us(a)["max"]),
        "\\midrule",
        f"\\multicolumn{{{ncol}}}{{l}}{{\\emph{{Funding scalar at "
        "settlement (USDT per BTC)}} \\\\",
        row("\\quad median $|F_t|$", lambda a: a["F_t_abs_median"], ".3f"),
        row("\\quad mean $|F_t|$", lambda a: a["F_t_abs_mean"], ".3f"),
        "\\bottomrule",
        "\\end{tabular}",
        (
            f"% params: strategy={params['strategy']}, "
            f"run_dir={params['run_dir']}, gamma={params['gamma']:g}, "
            f"Q={params['Q']}, rho={params['rho']:g}, "
            f"sigma_col={params['sigma_col']}, "
            f"switch read from pnl `regime` column (first regime==2 tick/epoch)"
        ),
    ]
    path.write_text("\n".join(lines) + "\n")


def write_figure(records: list[dict], path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({"font.size": 9, "axes.labelsize": 8.5,
                         "xtick.labelsize": 8, "ytick.labelsize": 8,
                         "legend.fontsize": 7.5, "axes.titlesize": 9.5})
    Ft = np.array([r["F_t"] for r in records])
    us = np.array([r["u_switch_s"] for r in records])
    split = np.array([r["split"] for r in records])

    fig, ax = plt.subplots(figsize=(6.3, 3.2))
    for name, label, mk, col in [
            ("pre_analysis", "pre-analysis", "^", "#888888"),
            ("sim", "out-of-sample", "o", "#1f77b4")]:
        m = split == name
        if not m.any():
            continue
        ax.scatter(Ft[m], us[m], s=16, marker=mk, alpha=0.6, color=col,
                   label=f"$u^*$ observed ({label})")
    ax.axhline(U_MAX_FLOOR_S, ls="--", lw=0.8, color="green",
               label=f"LUT horizon floor ({U_MAX_FLOOR_S:.0f} s)")
    ax.set_xlabel(r"funding scalar $F_t = S_{\mathrm{ref}} f_t$ at settlement")
    ax.set_ylabel(r"switch lead $u^*$ (s)")
    ax.grid(alpha=0.3)
    ax.legend(loc="upper right", framealpha=0.9)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    fig.savefig(path.with_suffix(".pdf"))
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", type=Path, default=BASE_DEFAULT)
    ap.add_argument("--run-dir", type=Path, default=RUN_DIR_DEFAULT,
                    help="ablation run dir containing s*/pnl_<fday>.parquet "
                         "")
    ap.add_argument("--strategy", type=str, default=STRATEGY_DEFAULT,
                    help="funding strategy subdir to read (s5 or s6)")
    ap.add_argument("--report-dir", type=Path,
                    default=Path(__file__).parent / "reports")
    ap.add_argument("--gamma", type=float, default=GAMMA_DEFAULT)
    ap.add_argument("--Q", type=int, default=Q_DEFAULT)
    ap.add_argument("--rho", type=float, default=RHO_DEFAULT)
    ap.add_argument("--epoch-s", type=float, default=EPOCH_S_DEFAULT)
    ap.add_argument("--sigma-col", type=str, default=SIGMA_COL_DEFAULT)
    args = ap.parse_args()


    splits = json.loads((args.base / "splits.json").read_text())["splits"]
    split_of: dict[str, str] = {}
    for split_name in ("pre_analysis", "sim"): # Should we maybe only use sim here?
        for d in splits[split_name]:
            split_of[d] = split_name

    sdir = args.run_dir / args.strategy
    records: list[dict] = []
    for d in sorted(split_of):
        pnl_path = sdir / f"pnl_{d}.parquet"
        if not pnl_path.exists():
            print(f"  {d}: skipped (no {pnl_path.name})")
            continue
        try:
            recs = census_day(
                args.base, d, gamma=args.gamma, Q=args.Q, rho=args.rho,
                epoch_s=args.epoch_s, sigma_col=args.sigma_col,
            )
        except FileNotFoundError as e:
            print(f"  {d}: skipped ({e})")
            continue
        if not recs:
            continue
        pnl = pl.read_parquet(pnl_path, columns=["ts_ms", "regime", "u_s"])
        switches = observed_switches(pnl, [r["ts_ms"] for r in recs])
        for r in recs:
            F_signed = r["mark"] * r["f"]   # census reports |F|; recover sign
            records.append({
                "fday": r["fday"],
                "ts_ms": r["ts_ms"],
                "split": split_of[d],
                "f": r["f"],
                "F_t": F_signed,
                "sigma_med_1h": r["sigma_med_1h"],
                "u_hat_s": r["u_hat_s"],
                "u_switch_s": switches[r["ts_ms"]],
            })
        print(f"  {d}: {len(recs)} settlements")

    aggs = {
        "pre_analysis": aggregate([r for r in records
                                   if r["split"] == "pre_analysis"]),
        "sim": aggregate([r for r in records if r["split"] == "sim"]),
        "all": aggregate(records),
    }
    params = {"strategy": args.strategy, "run_dir": str(args.run_dir),
              "gamma": args.gamma, "Q": args.Q, "rho": args.rho,
              "epoch_s": args.epoch_s, "sigma_col": args.sigma_col}
    args.report_dir.mkdir(parents=True, exist_ok=True)
    (args.report_dir / "boundary_layer.json").write_text(
        json.dumps({"params": params, "aggregates": aggs,
                    "settlements": records}, indent=2))
    write_tex(aggs, args.report_dir / "tab_boundary_layer.tex", params)
    write_figure(records, args.report_dir / "fig_boundary_layer.png")

    a = aggs["all"]
    if not a.get("n"):
        print("no settlements read; check --run-dir / --strategy")
        return
    print(f"\n{a['n']} settlements, layer switches on "
          f"{100*a['frac_layer_switches']:.1f}%")
    us = a["u_switch_s"]
    print(f"u* observed (switching): min {us['min']:.0f}  "
          f"median {us['median']:.0f}  mean {us['mean']:.0f}  "
          f"max {us['max']:.0f} s")
    print(f"|F_t| median {a['F_t_abs_median']:.3f}  "
          f"mean {a['F_t_abs_mean']:.3f}")
    print(f"wrote boundary_layer.json, tab_boundary_layer.tex, "
          f"fig_boundary_layer.png to {args.report_dir}")


if __name__ == "__main__":
    main()
