"""Boundary-layer activation census across all settlements."""
from __future__ import annotations

import argparse
import json
import math
from datetime import timedelta
from pathlib import Path

import numpy as np
import polars as pl

from pipeline_utils import (
    funding_day_bounds,
    funding_day_paths,
    funding_settlement_times,
    parse_date,
)

BASE_DEFAULT = Path("/mnt/rowan_thuis/Crypto_recorder/Merged_new/btcusdt")

GAMMA_DEFAULT = 2e-5
Q_DEFAULT = 10
RHO_DEFAULT = 6.46e-3  # production rho = spectral gap of M at queue-aware (A,k);
EPOCH_S_DEFAULT = 8 * 3600
SIGMA_COL_DEFAULT = "sigma"
PRE_WINDOW_S = 3600


def rho_tilde(rho: float, epoch_s: float) -> float:
    return rho / (1.0 - math.exp(-rho * epoch_s))


def census_day(
    base: Path, fday: str, *, gamma: float, Q: int, rho: float,
    epoch_s: float, sigma_col: str,
) -> list[dict]:
    """Per-settlement records for one funding day (04:00 -> 04:00 UTC)."""
    start_ms, end_ms = funding_day_bounds(fday)
    cands = sorted({
        s for d, _ in funding_day_paths(base, fday)
        for s in funding_settlement_times(d)
        if start_ms < s <= end_ms
    })
    next_day = (parse_date(fday) + timedelta(days=1)).strftime("%Y-%m-%d")
    srcs = [base / fday / "markprice_ffill_*.parquet"]
    if (base / next_day).is_dir():
        srcs.append(base / next_day / "markprice_ffill_0[0-3]h.parquet")
    mp = (
        pl.scan_parquet(srcs, allow_missing_columns=True)
        .select("ts_ms", "MarkPrice", "FundingRate")
        .collect()
        .sort("ts_ms")
    )
    vol = pl.read_parquet(
        base / "volatility" / f"volatility_{fday}.parquet",
        columns=["ts_ms", sigma_col],
    ).sort("ts_ms")

    rt = rho_tilde(rho, epoch_s)
    out: list[dict] = []
    for t in cands:
        pre = mp.filter(pl.col("ts_ms") <= t - 1000)
        if pre.is_empty():
            continue
        row = pre.row(-1, named=True)
        f = row["FundingRate"]
        mark = row["MarkPrice"]
        if f is None or mark is None:
            continue
        sig_win = vol.filter(
            (pl.col("ts_ms") > t - PRE_WINDOW_S * 1000) & (pl.col("ts_ms") <= t)
        )[sigma_col]
        sig_win = sig_win.filter(sig_win > 0)
        if sig_win.is_empty():
            continue
        sigma = float(sig_win.median())
        F = abs(mark * f)
        thr = gamma * sigma * sigma * Q / 2.0
        ratio = (rt * F / thr) if thr > 0 else float("inf")
        u_hat = (1.0 / rho) * math.log(ratio) if ratio > 1.0 else 0.0
        out.append({
            "fday": fday,
            "ts_ms": int(t),
            "f": float(f),
            "abs_f": abs(float(f)),
            "mark": float(mark),
            "F_abs": F,
            "sigma_med_1h": sigma,
            "ratio": float(ratio),
            "layer_forms": bool(ratio > 1.0),
            "u_hat_s": float(u_hat),
        })
    return out


def aggregate(records: list[dict]) -> dict:
    if not records:
        return {"n": 0}
    absf = np.array([r["abs_f"] for r in records])
    ratio = np.array([r["ratio"] for r in records])
    uhat = np.array([r["u_hat_s"] for r in records])
    formed = np.array([r["layer_forms"] for r in records])
    formed_u = uhat[formed] if formed.any() else np.array([0.0])
    return {
        "n": len(records),
        "abs_f_med": float(np.median(absf)),
        "abs_f_p90": float(np.quantile(absf, 0.9)),
        "abs_f_max": float(absf.max()),
        "ratio_med": float(np.median(ratio)),
        "frac_layer_forms": float(formed.mean()),
        "u_hat_med_s_when_formed": float(np.median(formed_u)),
        "u_hat_p90_s_when_formed": float(np.quantile(formed_u, 0.9)),
        "u_hat_max_s": float(uhat.max()),
        "frac_u_hat_gt_1h": float((uhat > 3600).mean()),
    }


def write_tex(aggs: dict[str, dict], path: Path, params: dict) -> None:
    a_pre, a_oos, a_all = aggs["pre_analysis"], aggs["sim"], aggs["all"]

    def row(label: str, key: str, fmt: str, scale: float = 1.0,
            pct: bool = False) -> str:
        def cell(a: dict) -> str:
            v = a[key] * (100.0 if pct else scale)
            return f"{v:{fmt}}\\%" if pct else f"{v:{fmt}}"
        return f"{label} & {cell(a_pre)} & {cell(a_oos)} & {cell(a_all)} \\\\"

    lines = [
        "% Auto-generated by analysis_funding_activation.py, do not edit.",
        "\\begin{tabular}{lrrr}",
        "\\toprule",
        " & Pre-analysis & Out-of-sample & All \\\\",
        "\\midrule",
        f"Settlements & {a_pre['n']} & {a_oos['n']} & {a_all['n']} \\\\",
        row("Median $|f|$ ($\\times 10^{-4}$)", "abs_f_med", ".2f", 1e4),
        row("P90 $|f|$ ($\\times 10^{-4}$)", "abs_f_p90", ".2f", 1e4),
        row("Median activation ratio", "ratio_med", ".1f"),
        row("Share with boundary layer", "frac_layer_forms", ".1f", pct=True),
        row("Median $\\hat{u}$ when formed (min)", "u_hat_med_s_when_formed",
            ".0f", 1 / 60),
        row("P90 $\\hat{u}$ when formed (min)", "u_hat_p90_s_when_formed",
            ".0f", 1 / 60),
        row("Share with $\\hat{u} > 1$\\,h", "frac_u_hat_gt_1h", ".1f",
            pct=True),
        "\\bottomrule",
        "\\end{tabular}",
        (
            f"% params: gamma={params['gamma']:g}, Q={params['Q']}, "
            f"rho={params['rho']:g}, epoch={params['epoch_s']:g}s, "
            f"sigma_col={params['sigma_col']}, sigma window = final "
            f"{PRE_WINDOW_S}s pre-settlement (median)"
        ),
    ]
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--base", type=Path, default=BASE_DEFAULT)
    ap.add_argument("--report-dir", type=Path,
                    default=Path(__file__).parent / "reports")
    ap.add_argument("--gamma", type=float, default=GAMMA_DEFAULT)
    ap.add_argument("--Q", type=int, default=Q_DEFAULT)
    ap.add_argument("--rho", type=float, default=RHO_DEFAULT)
    ap.add_argument("--epoch-s", type=float, default=EPOCH_S_DEFAULT)
    ap.add_argument("--sigma-col", type=str, default=SIGMA_COL_DEFAULT)
    args = ap.parse_args()


    splits = json.loads((args.base / "splits.json").read_text())["splits"]
    records: list[dict] = []
    split_of: dict[str, str] = {}
    for split_name in ("pre_analysis", "sim"):
        for d in splits[split_name]:
            split_of[d] = split_name
    for d in sorted(split_of):
        try:
            recs = census_day(
                args.base, d, gamma=args.gamma, Q=args.Q, rho=args.rho,
                epoch_s=args.epoch_s, sigma_col=args.sigma_col,
            )
        except FileNotFoundError as e:
            print(f"  {d}: skipped ({e})")
            continue
        for r in recs:
            r["split"] = split_of[d]
        records.extend(recs)
        print(f"  {d}: {len(recs)} settlements")

    aggs = {
        "pre_analysis": aggregate([r for r in records
                                   if r["split"] == "pre_analysis"]),
        "sim": aggregate([r for r in records if r["split"] == "sim"]),
        "all": aggregate(records),
    }
    params = {"gamma": args.gamma, "Q": args.Q, "rho": args.rho,
              "epoch_s": args.epoch_s, "sigma_col": args.sigma_col}
    args.report_dir.mkdir(parents=True, exist_ok=True)
    (args.report_dir / "funding_activation.json").write_text(
        json.dumps({"params": params, "aggregates": aggs,
                    "settlements": records}, indent=2)
    )
    write_tex(aggs, args.report_dir / "tab_funding_activation.tex", params)
    print(json.dumps(aggs, indent=2))
    print(f"-> {args.report_dir / 'funding_activation.json'}")
    print(f"-> {args.report_dir / 'tab_funding_activation.tex'}")


if __name__ == "__main__":
    main()
