"""Fill intensity and per-fill markout by ML signal tier."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import polars as pl

BASE = Path("/mnt/rowan_thuis/Crypto_recorder/Merged_new/btcusdt")
RUN_DEFAULT = Path("reports/rerun_20260807_ar/ablation_h10_qa")
ALPHA_DEFAULT = BASE / "models/alpha_h10/alpha_ml_h10.parquet"
TIERS = ("T1", "T2", "T3")


def time_tier_edges(alpha: pl.DataFrame, days: list[str]) -> tuple[float, float]:
    """Terciles of |alpha| over the 1 Hz grid."""
    a = (alpha.filter(pl.col("funding_day").is_in(days))
         .select(pl.col("alpha_ml").abs().alias("a"))
         .filter(pl.col("a") > 0)["a"])
    return float(a.quantile(1 / 3)), float(a.quantile(2 / 3))


def tier_expr(t1: float, t2: float) -> pl.Expr:
    a = pl.col("alpha_ml").abs()
    return (pl.when(a <= t1).then(pl.lit("T1"))
            .when(a <= t2).then(pl.lit("T2"))
            .otherwise(pl.lit("T3")))


def build(fills: pl.DataFrame, alpha: pl.DataFrame) -> dict:
    days = sorted(fills["funding_day"].unique().to_list())
    t1, t2 = time_tier_edges(alpha, days)
    live_h = (alpha.filter(pl.col("funding_day").is_in(days))
              .select((pl.col("alpha_ml").abs() > 0).sum()).item()) / 3600.0
    # time share per tier, over seconds with a nonzero signal
    ag = (alpha.filter(pl.col("funding_day").is_in(days))
          .filter(pl.col("alpha_ml").abs() > 0)
          .with_columns(tier_expr(t1, t2).alias("atier"))
          .group_by("atier").agg(pl.len().alias("secs")).sort("atier"))
    secs = dict(zip(ag["atier"], ag["secs"]))
    tot_secs = sum(secs.values())

    f = (fills.filter(~pl.col("is_liquidation"))
         .filter(pl.col("alpha_ml").abs() > 0)
         .with_columns(
             tier_expr(t1, t2).alias("atier"),
             (pl.when(pl.col("alpha_ml") * pl.col("side") > 0)
              .then(pl.lit("aligned")).otherwise(pl.lit("counter"))
              ).alias("bucket")))

    out: dict = {"tier_edges": [t1, t2], "days": len(days),
                 "live_hours_nonzero_signal": live_h,
                 "time_share": {k: secs.get(k, 0) / tot_secs for k in TIERS}}
    for s in sorted(f["strategy"].unique().to_list()):
        sub = f.filter(pl.col("strategy") == s)
        g = (sub.group_by(["atier", "bucket"])
             .agg(pl.len().alias("n"),
                  pl.col("mo_1s").drop_nans().mean().alias("mo1"),
                  pl.col("mo_5s").drop_nans().mean().alias("mo5"),
                  pl.col("mo_30s").drop_nans().mean().alias("mo30"))
             .sort(["atier", "bucket"]))
        per_tier = (sub.group_by("atier").agg(pl.len().alias("n"))
                    .sort("atier"))
        out[f"s{s}"] = {
            "buckets": g.to_dicts(),
            "fills_per_hour_by_tier": {
                r["atier"]: r["n"] / (secs.get(r["atier"], 1) / 3600.0)
                for r in per_tier.to_dicts()},
            "n_total": sub.height,
        }
    return out


def write_tex(res: dict, rep: Path, ref: int, ml: int) -> None:
    rs, ms = res[f"s{ref}"], res[f"s{ml}"]
    rb = {(d["atier"], d["bucket"]): d for d in rs["buckets"]}
    mb = {(d["atier"], d["bucket"]): d for d in ms["buckets"]}
    lines = [
        "% generated by analysis_fill_timing.py",
        r"\begin{tabular}{llrrrr}", r"\toprule",
        (r"$|\alpha|$ tier & side & fills/h (GLT) & fills/h (ML) & "
         r"ratio & GLT 5\,s markout (bps) \\"), r"\midrule"]
    for t in TIERS:
        for b in ("aligned", "counter"):
            r, m = rb.get((t, b)), mb.get((t, b))
            if r is None:
                continue
            hrs_t = res["time_share"][t] * res["live_hours_nonzero_signal"]
            fr, fm = r["n"] / hrs_t, (m["n"] / hrs_t if m else float("nan"))
            lines.append(
                f"{t} & {b} & {fr:,.0f} & {fm:,.0f} & "
                f"{(fm / fr):.2f} & {r['mo5']:.2f} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    (rep / "tab_fill_timing.tex").write_text("\n".join(lines))


def decile_check(fills: pl.DataFrame, alpha: pl.DataFrame,
                 ref: int = 2, ml: int = 4) -> dict:
    """Same profile on time-weighted |alpha| deciles."""
    days = sorted(fills["funding_day"].unique().to_list())
    g = (alpha.filter(pl.col("funding_day").is_in(days))
         .filter(pl.col("alpha_ml").abs() > 0))
    edges = [float(g["alpha_ml"].abs().quantile(q / 10)) for q in range(1, 10)]

    def dec(col: str) -> pl.Expr:
        e = pl.col(col).abs()
        expr = pl.when(e <= edges[0]).then(0)
        for i in range(1, 9):
            expr = expr.when(e <= edges[i]).then(i)
        return expr.otherwise(9).alias("dec")

    secs = dict(g.with_columns(dec("alpha_ml")).group_by("dec")
                .agg(pl.len().alias("s")).sort("dec").iter_rows())
    f = (fills.filter(~pl.col("is_liquidation")
                      & (pl.col("alpha_ml").abs() > 0)
                      & pl.col("strategy").is_in([ref, ml]))
         .with_columns(dec("alpha_ml"),
                       (pl.col("alpha_ml") * pl.col("side") > 0)
                       .alias("aligned")))
    tab = (f.group_by(["strategy", "dec", "aligned"])
           .agg(pl.len().alias("n"),
                pl.col("mo_5s").drop_nans().mean().alias("mo5"))
           .sort(["strategy", "dec", "aligned"]))
    d = {(r["strategy"], r["dec"], r["aligned"]): (r["n"], r["mo5"])
         for r in tab.to_dicts()}
    rows = []
    for i in range(10):
        h = secs.get(i, 1) / 3600.0
        n_ref = d.get((ref, i, False), (0,))[0] + d.get((ref, i, True), (0,))[0]
        rows.append({
            "decile": i,
            "ref_fills_per_h": n_ref / h,
            "ratio_counter": (d.get((ml, i, False), (float("nan"),))[0]
                              / max(d.get((ref, i, False), (1,))[0], 1)),
            "ratio_aligned": (d.get((ml, i, True), (float("nan"),))[0]
                              / max(d.get((ref, i, True), (1,))[0], 1)),
            "ref_mo5_counter": d.get((ref, i, False), (0, float("nan")))[1],
            "ref_mo5_aligned": d.get((ref, i, True), (0, float("nan")))[1],
        })
    return {"edges": edges, "rows": rows}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--markout-fills", type=Path,
                    default=RUN_DEFAULT / "markout_fills.parquet")
    ap.add_argument("--alpha-parquet", type=Path, default=ALPHA_DEFAULT)
    ap.add_argument("--report-dir", type=Path,
                    default=Path("reports/rerun_20260807_ar/fill_timing"))
    ap.add_argument("--ref-strategy", type=int, default=2)
    ap.add_argument("--ml-strategy", type=int, default=4)
    args = ap.parse_args()
    fills = pl.read_parquet(args.markout_fills)
    alpha = pl.read_parquet(args.alpha_parquet)
    if "alpha_ml" not in alpha.columns:
        # ml_predict.py schema
        alpha = alpha.rename({"alpha_ml_usdt_s": "alpha_ml",
                              "test_day": "funding_day"})
    res = build(fills, alpha)
    args.report_dir.mkdir(parents=True, exist_ok=True)
    write_tex(res, args.report_dir, args.ref_strategy, args.ml_strategy)
    (args.report_dir / "fill_timing.json").write_text(json.dumps(res, indent=1))
    decs = decile_check(fills, alpha, args.ref_strategy, args.ml_strategy)
    (args.report_dir / "fill_timing_deciles.json").write_text(
        json.dumps(decs, indent=1))
    print(json.dumps({"time_share": res["time_share"],
                      "s2_fph": res.get("s2", {}).get("fills_per_hour_by_tier"),
                      "s4_fph": res.get("s4", {}).get("fills_per_hour_by_tier")},
                     indent=1))
    print("written:", args.report_dir)


if __name__ == "__main__":
    main()
