"""Cross-symbol funding-rate distributions from the Binance public API."""
from __future__ import annotations

import argparse
import json
import time
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

BASE = "https://fapi.binance.com"
SYMBOLS = ["BTCUSDT", "ETHUSDT", "SOLUSDT", "XRPUSDT", "DOGEUSDT",
           "AVAXUSDT", "1000PEPEUSDT", "WIFUSDT", "TRBUSDT", "LPTUSDT"]
DOC_CARRY = 5.5e-4     # documented-carry scenario level (stress suite); sits just
BTC_CAP = 3.0e-3       # Binance BTCUSDT clamp per settlement
GENERIC_CAP = 2.0e-2   # generic-tier clamp
PAGES = 8              # pages of history back from now (server caps rows/page)


def _get(path: str, params: dict) -> list | dict:
    qs = "&".join(f"{k}={v}" for k, v in params.items())
    url = f"{BASE}{path}?{qs}" if qs else f"{BASE}{path}"
    with urllib.request.urlopen(url, timeout=20) as r:
        return json.loads(r.read().decode())


def fetch_history(symbol: str, pages: int = PAGES) -> tuple[np.ndarray, np.ndarray]:
    """Funding-rate history, newest-last: (funding_time_ms, rate)."""
    ts_all: list[int] = []
    fr_all: list[float] = []
    end = int(time.time() * 1000)
    for _ in range(pages):
        rows = _get("/fapi/v1/fundingRate",
                    {"symbol": symbol, "limit": 1000, "endTime": end})
        if not rows:
            break
        rows.sort(key=lambda r: r["fundingTime"])
        ts_all = [int(r["fundingTime"]) for r in rows] + ts_all
        fr_all = [float(r["fundingRate"]) for r in rows] + fr_all
        end = int(rows[0]["fundingTime"]) - 1
        if len(rows) < 2:
            break
        time.sleep(0.3)
    return np.asarray(ts_all, dtype=np.int64), np.asarray(fr_all)


def summarize(ts: np.ndarray, f: np.ndarray, cap: float,
              interval_h: float) -> dict:
    """Distributional facts for one symbol's realised funding history."""
    a = np.abs(f)
    return {
        "n_settlements": int(f.size),
        "first": datetime.fromtimestamp(ts[0] / 1e3, tz=timezone.utc)
        .strftime("%Y-%m-%d") if ts.size else None,
        "last": datetime.fromtimestamp(ts[-1] / 1e3, tz=timezone.utc)
        .strftime("%Y-%m-%d") if ts.size else None,
        "interval_h": interval_h,
        "cap": cap,
        "median_abs_f": float(np.median(a)),
        "p90_abs_f": float(np.quantile(a, 0.90)),
        "p99_abs_f": float(np.quantile(a, 0.99)),
        "max_abs_f": float(a.max()) if a.size else None,
        "median_ann": float(np.median(a) * (24.0 / interval_h) * 365.0),
        "frac_ge_doc_carry": float((a >= DOC_CARRY).mean()),
        "frac_ge_btc_cap": float((a >= BTC_CAP).mean()),
        "frac_near_own_cap": float((a >= 0.9 * cap).mean()),
    }


def infer_interval_h(ts: np.ndarray) -> float:
    """Modal settlement spacing in hours (robust to the 1h cap-hit rule)."""
    if ts.size < 3:
        return 8.0
    d = np.diff(ts) / 3.6e6
    vals, counts = np.unique(np.round(d).astype(int), return_counts=True)
    return float(vals[np.argmax(counts)])


def write_tex(stats: dict[str, dict], path: Path, accessed: str) -> None:
    lines = [
        "% Auto-generated by fetch_altcoin_funding.py, do not edit.",
        r"\setlength{\tabcolsep}{4.5pt}",
        r"\begin{tabular}{lrrrrrrr}", r"\toprule",
        r" & & & \multicolumn{3}{c}{$|f|$ per settlement (bp)}"
        r" & \multicolumn{2}{c}{settlements (\%)} \\",
        r"\cmidrule(lr){4-6}\cmidrule(lr){7-8}",
        r"Symbol & Int.\ (h) & Cap$^{\dagger}$ & median & P99 & max"
        r" & $\ge$ doc.\ carry & $\ge$ BTC cap \\",
        r"\midrule",
    ]
    for sym, s in stats.items():
        lines.append(
            f"{sym} & {s['interval_h']:.0f} & {1e4 * s['cap']:,.0f} & "
            f"{1e4 * s['median_abs_f']:.2f} & {1e4 * s['p99_abs_f']:.1f} & "
            f"{1e4 * s['max_abs_f']:.1f} & "
            f"{100 * s['frac_ge_doc_carry']:.1f} & "
            f"{100 * s['frac_ge_btc_cap']:.2f} \\\\")
    lines += [
        r"\bottomrule", r"\end{tabular}",
        f"% source: Binance /fapi/v1/fundingRate + /fapi/v1/fundingInfo,"
        f" accessed {accessed}; doc. carry = 5.5e-4 per settlement"
        f" (stress-suite scenario level); BTC cap = 3e-3.",
        r"% dagger: caps are the CURRENT per-symbol clamps as accessed;"
        r" Binance adjusts caps in extreme conditions, so historical rates"
        r" may exceed the current value.",
    ]
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--out-dir", type=Path,
                    default=Path(__file__).parent / "reports/altcoin_funding")
    args = ap.parse_args()

    accessed = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d")
    info = {r["symbol"]: r for r in _get("/fapi/v1/fundingInfo", {})}
    stats: dict[str, dict] = {}
    for sym in SYMBOLS:
        ts, f = fetch_history(sym)
        interval = infer_interval_h(ts)
        cap = (float(info[sym]["adjustedFundingRateCap"]) if sym in info
               else (BTC_CAP if sym in ("BTCUSDT", "ETHUSDT")
                     else GENERIC_CAP))
        stats[sym] = summarize(ts, f, cap=cap, interval_h=interval)
        print(f"{sym:14s} n={stats[sym]['n_settlements']:5d} "
              f"int={interval:.0f}h cap={1e4 * cap:5.0f}bp "
              f"med|f|={1e4 * stats[sym]['median_abs_f']:6.2f}bp "
              f"p99={1e4 * stats[sym]['p99_abs_f']:6.1f}bp "
              f"max={1e4 * stats[sym]['max_abs_f']:7.1f}bp "
              f">=doc {100 * stats[sym]['frac_ge_doc_carry']:5.1f}% "
              f">=btccap {100 * stats[sym]['frac_ge_btc_cap']:5.2f}%")

    args.out_dir.mkdir(parents=True, exist_ok=True)
    (args.out_dir / "altcoin_funding.json").write_text(json.dumps(
        {"accessed_utc": accessed, "symbols": stats,
         "doc_carry": DOC_CARRY, "btc_cap": BTC_CAP,
         "generic_cap": GENERIC_CAP,
         "source": "Binance /fapi/v1/fundingRate + /fapi/v1/fundingInfo"},
        indent=2))
    write_tex(stats, args.out_dir / "tab_altcoin_funding.tex", accessed)
    print(f"\nwrote {args.out_dir}/altcoin_funding.json + tab_altcoin_funding.tex")


if __name__ == "__main__":
    main()
