"""Accuracy of the Regime-I Gaussian closed form."""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path

import numpy as np

from hjb_principal_eigenvector import (
    HJBParams,
    discrete_autonomous_quotes,
    gaussian_eigvec,
    principal_eigvec,
    q_grid,
)
from sim_quote_engine import MarketConsts, glt_depths

GAMMA_DEFAULT = 2.0e-5
SIGMA_DEFAULT = 4.575
A_DEFAULT = 0.2742
K_DEFAULT = 0.0900
Q_DEFAULT = 10
TICK_DEFAULT = 0.1


def _weighted_std(values: np.ndarray, weights: np.ndarray) -> float:
    """Std of an inventory shape treated as (unnormalised) weights, about 0."""
    w = weights / weights.sum()
    mean = float((w * values).sum())
    var = float((w * (values - mean) ** 2).sum())
    return math.sqrt(max(var, 0.0))


def analyse(gamma: float, sigma: float, A: float, k: float, Q: int,
            tick: float) -> dict:
    p = HJBParams(gamma=gamma, sigma=sigma, A=A, k=k, alpha_ml=0.0, Q=Q)
    mc = MarketConsts(gamma, sigma, A, k)
    q = q_grid(Q)  # Q .. -Q

    ratio_ae = p.alpha / p.eta
    sigma_q_theory = ratio_ae ** -0.25                  # (alpha/eta)^{-1/4}
    spacing_to_width = 1.0 / sigma_q_theory             # unit lot / width
    f0_exact = principal_eigvec(p)                      # exact, ordered Q..-Q
    f0_gauss = gaussian_eigvec(p)
    sigma_q_exact = _weighted_std(q, f0_exact)
    sigma_q_gauss = _weighted_std(q, f0_gauss)

    z = (Q + 0.5) / sigma_q_theory
    trunc_mass = math.erfc(z / math.sqrt(2.0))          # two-sided tail

    db_ex, da_ex = discrete_autonomous_quotes(p)        # indexed q + Q (asc)
    per_absq: dict[int, dict] = {}
    worst = {"q": None, "side": None, "ticks": 0.0}
    for qi in range(-Q, Q + 1):
        db_g, da_g = glt_depths(mc, qi, 0.0)
        for side, approx, exact in (("bid", db_g, db_ex[qi + Q]),
                                    ("ask", da_g, da_ex[qi + Q])):
            if not math.isfinite(exact):                # capacity edge: no quote
                continue
            e = abs(approx - exact) / tick
            slot = per_absq.setdefault(abs(qi), {"err_ticks": 0.0, "depth": 0.0})
            slot["err_ticks"] = max(slot["err_ticks"], e)
            slot["depth"] = max(slot["depth"], approx)   # deeper of the two sides
            if e > worst["ticks"]:
                worst = {"q": qi, "side": side, "ticks": e,
                         "glt": approx, "exact": exact}
    for aq, slot in per_absq.items():
        slot["fill_intensity_per_s"] = A * math.exp(-k * slot["depth"])

    half = Q // 2
    err_moderate = max(per_absq[aq]["err_ticks"] for aq in per_absq if aq <= half)
    err_near_cap = max(per_absq[aq]["err_ticks"] for aq in per_absq if aq > half)

    return {
        "params": {"gamma": gamma, "sigma": sigma, "A": A, "k": k, "Q": Q,
                   "tick": tick},
        "alpha": p.alpha, "eta": p.eta,
        "sigma_q_lots_theory": sigma_q_theory,
        "sigma_q_lots_exact": sigma_q_exact,
        "sigma_q_lots_gauss": sigma_q_gauss,
        "spacing_to_width": spacing_to_width,
        "trunc_mass_beyond_Q": trunc_mass,
        "quote_err_moderate_ticks": err_moderate,   # |q| <= Q//2
        "quote_err_near_cap_ticks": err_near_cap,   # |q| >  Q//2
        "quote_err_worst": worst,
        "profile_by_absq": {aq: per_absq[aq] for aq in sorted(per_absq)},
    }


def write_tex(r: dict, path: Path) -> None:
    lines = [
        "% Auto-generated by validate_gaussian_asymptotic.py, do not edit.",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Quantity & Value \\\\",
        "\\midrule",
        f"Eigenvector width $\\sigma_q$ (lots) & {r['sigma_q_lots_theory']:.2f} \\\\",
        f"Lattice spacing / width & {r['spacing_to_width']:.3f} \\\\",
        f"Exact vs Gaussian $\\sigma_q$ (lots) & "
        f"{r['sigma_q_lots_exact']:.2f} / {r['sigma_q_lots_gauss']:.2f} \\\\",
        f"Untruncated Gaussian mass beyond $\\pm Q$ & "
        f"{r['trunc_mass_beyond_Q']:.1e} \\\\",
        f"Max quote error, $|q|\\le Q/2$ (ticks) & "
        f"{r['quote_err_moderate_ticks']:.2f} \\\\",
        f"Max quote error, $|q|> Q/2$ (ticks) & "
        f"{r['quote_err_near_cap_ticks']:.2f} \\\\",
        "\\bottomrule",
        "\\end{tabular}",
        (f"% params: gamma={r['params']['gamma']:g}, sigma={r['params']['sigma']:g}, "
         f"A={r['params']['A']:g}, k={r['params']['k']:g}, Q={r['params']['Q']}, "
         f"tick={r['params']['tick']:g}"),
    ]
    path.write_text("\n".join(lines) + "\n")


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--gamma", type=float, default=GAMMA_DEFAULT)
    ap.add_argument("--sigma", type=float, default=SIGMA_DEFAULT)
    ap.add_argument("--A", type=float, default=A_DEFAULT)
    ap.add_argument("--k", type=float, default=K_DEFAULT)
    ap.add_argument("--Q", type=int, default=Q_DEFAULT)
    ap.add_argument("--tick", type=float, default=TICK_DEFAULT)
    ap.add_argument("--report-dir", type=Path,
                    default=Path(__file__).parent / "reports")
    args = ap.parse_args()


    r = analyse(args.gamma, args.sigma, args.A, args.k, args.Q, args.tick)
    args.report_dir.mkdir(parents=True, exist_ok=True)
    (args.report_dir / "gaussian_asymptotic.json").write_text(
        json.dumps(r, indent=2))
    write_tex(r, args.report_dir / "tab_gaussian_asymptotic.tex")
    print(json.dumps(r, indent=2))
    print(f"-> {args.report_dir / 'gaussian_asymptotic.json'}")
    print(f"-> {args.report_dir / 'tab_gaussian_asymptotic.tex'}")


if __name__ == "__main__":
    main()
